name: epi2melabs-nf-denovo-assembly
channels:
    - epi2melabs
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python==3.8.*
    - bokeh==2.4.3
    - aplanat >=0.5.0
    - pysam >=0.17.0
    - fastcat
    - epi2melabs
    - pandas
    - flye
    - quast >=5.2.0
